version: '3'
services:
    docker-golang:
        build: 
            context: ./golang/centos
            dockerfile: Dockerfile
        container_name: docker-golang
        hostname: docker-golang
        networks: 
            webserver:
                ipv4_address: 172.52.1.2
        links:
            - docker-redis
            - docker-mysql
            - docker-mongodb
        volumes: 
            - "./admin:/wwwroot/admin"
        tty: true
    docker-nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: docker-nginx
        hostname: docker-nginx
        networks: 
            webserver:
                ipv4_address: 172.52.1.3
        links:
            - docker-golang
        ports:
            - "80:80"
            - "8888:8888"
        # depends_on:
        #     - golang
        volumes:
            - "./admin:/wwwroot/admin"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/conf:/etc/nginx/conf"
    docker-redis:
        build: 
            context: ./redis
            dockerfile: Dockerfile
        container_name: docker-redis
        hostname: docker-redis
        logging:
            driver: none
        ports:
            - "16379:6379"
        networks: 
            webserver:
                ipv4_address: 172.52.1.4
        volumes:
            - ./redis/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/data/redis/:/data
    docker-mongodb:
        build: 
            context: ./mongodb
            dockerfile: Dockerfile
        container_name: docker-mongodb
        hostname: docker-mongodb
        logging:
            driver: none
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: mongodb
        ports:
            - "27017:27017"
        networks:
            webserver:
                ipv4_address: 172.52.1.5
    docker-mysql:
        build: 
            context: ./mysql
            dockerfile: Dockerfile
        container_name: docker-mysql
        hostname: docker-mysql
        networks: 
            webserver:
                ipv4_address: 172.52.1.6
        ports:
            - "13066:3306"
        command: --default-authentication-plugin=mysql_native_password
        #restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        volumes:
            - "./mysql/data/:/var/lib/mysql/"
networks: 
    webserver:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: "172.52.1.0/24"

#docker stop $(docker ps -q) & docker rm $(docker ps -aq)
